FROM python:3.13-slim

# Set workdir
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy code
COPY . .

# Expose both ports
EXPOSE 8501 


# Start FastAPI and Streamlit together
CMD bash -c "streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0 & uvicorn src.confidence_crew.main:app --host 0.0.0.0 --port 8000"
