cv_analysis_task:
  description: >
    Analyze the provided CV text: {cv_text}.
    Focus on:
    1. Structure and Formatting: Is it clean, professional, and easy to read?
    2. Content Quality: Does it use strong action verbs and quantify achievements?
    3. Completeness: Are standard sections (Contact, Experience, Education, Skills) present?
    Provide a summary of strengths and areas for improvement.
  expected_output: >
    A structured report in Markdown format with sections for 'Strengths' and
    'Areas for Improvement' based on the CV's structure, formatting, and content.
  agent: cv_analyst

repo_review_task:
  description: >
    For each GitHub URL provided in {github_urls}, use your tool to analyze the repository.
    If the list of URLs is empty, you MUST state that this step was skipped.
    Synthesize the findings from all repositories into a single summary.
    Focus on assessing the technical skills demonstrated, code quality, and project documentation.
  expected_output: >
    A summary of the technical analysis from the GitHub repositories.
    Mention the key skills observed and the overall quality of the projects.
    If no URLs were given, return 'No GitHub repositories were provided for analysis.'
  agent: tech_talent_assessor

career_strategy_task:
  description: >
    Synthesize the insights from the CV Analysis and the GitHub Repository Review.
    Create a final, comprehensive report for the user. The report must be encouraging
    and highly actionable.
  expected_output: >
    A comprehensive and well-structured report in Markdown format with the following sections:
    1. **Overall CV Score:** An estimated score out of 10, with a brief justification.
    2. **Detailed Breakdown:**
       - **CV Structure & Content:** A summary of findings from the CV analysis.
       - **Technical Skills Showcase:** A summary of findings from the repository review.
    3. **Top 3 Actionable Suggestions:** A bulleted list of the most critical improvements.
    4. **Suggested Job Roles:** A list of 3-5 job titles that would be a good fit.
  agent: career_strategist